export const RELEASES = [
  {
    id: 1,
    title: 'DAKNAM',
    artist: 'OOLKA',
    featured: 'Ibn Khalid Khan, Rafsan Jani',
    releaseDate: '1/5/2026',
    genre: 'Rock',
    subgenre: 'Hard Rock',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan, Rafsan Jani',
    explicit: false,
    songwriter: 'NIL',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/7bVbQQXW2VF9MPGawVbSck?si=a732742fe0664be2',
    coverImage: '/covers/Daknam.png',
    spotifyId: "7bVbQQXW2VF9MPGawVbSck",
  },
  {
    id: 2,
    title: 'CHUTI CHAY',
    artist: 'OOLKA',
    featured: 'Ibn Khalid Khan, Rafsan Jani',
    releaseDate: '1/4/2026',
    genre: 'Rock',
    subgenre: 'Hard Rock',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan, Rafsan Jani',
    explicit: false,
    songwriter: 'NIL',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/02jzmdKJhxFL85nHrGsXGa?autoplay_ok=1',
    coverImage: '/covers/Chuti_Chay.png',
    spotifyId: '02jzmdKJhxFL85nHrGsXGa',
  },
  {
    id: 3,
    title: 'EPISTOSIX',
    artist: 'OOLKA',
    featured: 'Ibn Khalid Khan',
    releaseDate: '12/16/2025',
    genre: 'Instrumental',
    subgenre: 'NIL',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan, Rafsan Jani',
    explicit: true,
    songwriter: 'NIL',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/2Zeo6jgapunY2AGjIWCRfC?autoplay_ok=1',
    coverImage: '/covers/Epistosix.png',
    spotifyId: '2Zeo6jgapunY2AGjIWCRfC',
  },
  {
    id: 4,
    title: 'ASTRAY',
    artist: 'OOLKA',
    featured: 'Ibn Khalid Khan, Rafsan Jani',
    releaseDate: '12/16/2026',
    genre: 'Rock',
    subgenre: 'Heavy Metal',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan, Rafsan Jani',
    explicit: true,
    songwriter: 'Raihan Rahee',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/2mon00XgUi4wyTKcReeTSH?autoplay_ok=1',
    coverImage: '/covers/Astray.png',
    spotifyId: '2mon00XgUi4wyTKcReeTSH',
  },
  {
    id: 5,
    title: 'QOOXX',
    artist: 'OOLKA',
    featured: 'Ibn Khalid Khan, Rafsan Jani',
    releaseDate: '12/8/2025',
    genre: 'Instrumental',
    subgenre: 'NIL',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan, Rafsan Jani',
    explicit: true,
    songwriter: 'NIL',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/5mIfootq1z2tcSpXuvb0fi?autoplay_ok=1',
    coverImage: '/covers/Qooxx.png',
    spotifyId: '5mIfootq1z2tcSpXuvb0fi',
  },
  {
    id: 6,
    title: 'SHEDIN DUPORE',
    artist: 'OOLKA',
    featured: 'Ibn Khalid Khan',
    releaseDate: 'Upcoming...',
    genre: 'Rock',
    subgenre: 'Blues Rock',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan',
    explicit: true,
    songwriter: 'Tashfique Kaif, Ibn Khalid Khan',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Shedin_Dupore.png',
    spotifyId: null,
  },
  {
    id: 7,
    title: 'KITPOKA',
    artist: 'Ibn Khalid Khan',
    featured: 'OOLKA, Rafsan Jani',
    releaseDate: '12/24/2025',
    genre: 'Rock',
    subgenre: 'Heavy Metal',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan, Rafsan Jani',
    explicit: false,
    songwriter: 'NIL',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/2zl8CckRz9rHsXEfVUPV3g?autoplay_ok=1',
    coverImage: '/covers/Kitpoka.png',
    spotifyId: '2zl8CckRz9rHsXEfVUPV3g',
  },
  {
    id: 8,
    title: 'TOMAR SHOHOR',
    artist: 'Ibn Khalid Khan',
    featured: 'Rafsan Jani',
    releaseDate: '12/21/2025',
    genre: 'Rock',
    subgenre: 'Blues Rock',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan',
    explicit: false,
    songwriter: 'Ibn Khalid Khan, Rafsan Jani',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/4FVdm77B5d9Nwnd1CcxRZh?autoplay_ok=1',
    coverImage: '/covers/Tomar_Shohor.png',
    spotifyId: '4FVdm77B5d9Nwnd1CcxRZh',
  },
  {
    id: 9,
    title: 'SHUNNOTA',
    artist: 'Ibn Khalid Khan',
    featured: 'Rafsan Jani',
    releaseDate: '12/21/2025',
    genre: 'Rock',
    subgenre: 'Heavy Metal',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan',
    explicit: false,
    songwriter: 'Ibn Khalid Khan, Rafsan Jani',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/08bIogREkOre5BazAsQatB?autoplay_ok=1',
    coverImage: '/covers/Shunnota.png',
    spotifyId: '08bIogREkOre5BazAsQatB',
  },
  {
    id: 10,
    title: 'ABSENCE',
    artist: 'Ibn Khalid Khan',
    featured: 'OOLKA',
    releaseDate: '12/24/2025',
    genre: 'Classical',
    subgenre: 'NIL',
    language: 'English',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan',
    explicit: true,
    songwriter: 'NIL',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/3PtY7ylBXJGmlAy52zF8hv?autoplay_ok=1',
    coverImage: '/covers/Absence.png',
    spotifyId: '3PtY7ylBXJGmlAy52zF8hv',
  },
  {
    id: 11,
    title: 'PANDAGIRL',
    artist: 'Ibn Khalid Khan',
    featured: 'NIL',
    releaseDate: '12/8/2025',
    genre: 'Rock',
    subgenre: 'Heavy Metal',
    language: 'English',
    type: 'Single',
    copyright: 'Ibn Khalid Khan',
    composer: 'Ibn Khalid Khan',
    explicit: false,
    songwriter: 'NIL',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/0xOoPPyAnuFQurEBEAy6nH?autoplay_ok=1',
    coverImage: '/covers/Pandagirl.png',
    spotifyId: '0xOoPPyAnuFQurEBEAy6nH',
  },
  {
    id: 12,
    title: 'BOSSIN',
    artist: 'Ibn Khalid Khan',
    featured: 'NIL',
    releaseDate: '2/26/2025',
    genre: 'Hip Hop',
    subgenre: 'NIL',
    language: 'English',
    type: 'Single',
    copyright: 'Ibn Khalid Khan',
    composer: 'Ibn Khalid Khan',
    explicit: true,
    songwriter: 'Ibn Khalid Khan',
    platform: 'Spotify',
    link: 'https://open.spotify.com/track/38FZwB4tlxngwE6XG1TCQR?autoplay_ok=1',
    coverImage: '/covers/Bossin.png',
    spotifyId: '38FZwB4tlxngwE6XG1TCQR',
  },
  {
    id: 13,
    title: 'BIBORNO',
    artist: 'OOLKA',
    featured: 'Upcoming...',
    releaseDate: 'Upcoming...',
    genre: 'Rock',
    subgenre: 'Prog Rock / Art Rock',
    language: 'Bengali',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan',
    explicit: true,
    songwriter: 'Ibn Khalid Khan, Afia Ibnat Snigdha',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Biborno.png',
    spotifyId: null,
  },
  {
    id: 14,
    title: 'BOTTLEBONDI',
    artist: 'Ibn Khalid Khan',
    featured: 'Upcoming...',
    releaseDate: 'Upcoming...',
    genre: 'Metal',
    subgenre: 'NIL',
    language: 'Bengali',
    type: 'Single',
    copyright: 'realwithus',
    composer: 'Ibn Khalid Khan',
    explicit: false,
    songwriter: 'Ibn Khalid Khan, Afia Ibnat Snigdha',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Bottlebondi.png',
    spotifyId: null,
  },
  {
    id: 15,
    title: 'MEGHER DANA',
    artist: 'Ibn Khalid Khan',
    featured: 'Upcoming...',
    releaseDate: 'Upcoming...',
    genre: 'Blues',
    subgenre: 'NIL',
    language: 'Bengali',
    type: 'Single',
    copyright: 'realwithus',
    composer: 'Ibn Khalid Khan',
    explicit: false,
    songwriter: 'Ibn Khalid Khan, Afia Ibnat Snigdha',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Megher_Dana.png',
    spotifyId: null,
  },
  {
    id: 16,
    title: 'OTHOI',
    artist: 'Ibn Khalid Khan',
    featured: 'Upcoming...',
    releaseDate: 'Upcoming...',
    genre: 'Blues',
    subgenre: 'NIL',
    language: 'Bengali',
    type: 'Single',
    copyright: 'realwithus',
    composer: 'Ibn Khalid Khan',
    explicit: false,
    songwriter: 'NIL',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Othoi.png',
    spotifyId: null,
  },
  {
    id: 17,
    title: 'JIBONER PORAJOY',
    artist: 'Ibn Khalid Khan',
    featured: 'NIL',
    releaseDate: 'Upcoming...',
    genre: 'Rock',
    subgenre: 'Hard Rock',
    language: 'Upcoming...',
    type: 'Single',
    copyright: 'Ibn Khalid Khan',
    composer: 'Afia Ibnat Snigdha',
    explicit: false,
    songwriter: 'Afia Ibnat Snigdha',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Jiboner_Porajoy.png',
    spotifyId: null,
  },
  {
    id: 18,
    title: 'GOLOKDHADHAR MAJHE',
    artist: 'Ibn Khalid Khan',
    featured: 'NIL',
    releaseDate: 'Upcoming...',
    genre: 'Blues',
    subgenre: 'NIL',
    language: 'Upcoming...',
    type: 'Single',
    copyright: 'Ibn Khalid Khan',
    composer: 'Ibn Khalid Khan',
    explicit: false,
    songwriter: 'Ibn Khalid Khan',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Golokdhadhar_Majhe.png',
    spotifyId: null,
  },
  {
    id: 19,
    title: 'SHEDIN DUPORE (REPRISE)',
    artist: 'OOLKA',
    featured: 'NIL',
    releaseDate: 'Upcoming...',
    genre: 'Metal',
    subgenre: 'NIL',
    language: 'Upcoming...',
    type: 'Single',
    copyright: 'OOLKA Productions',
    composer: 'Ibn Khalid Khan, Afia Ibnat Snigdha',
    explicit: true,
    songwriter: 'Ibn Khalid Khan, Afia Ibnat Snigdha',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Shedin_Dupore_Reprise.png',
    spotifyId: null,
  },
  {
    id: 20,
    title: 'ONNO GROHER CHAND (REIMAGINED)',
    artist: 'Ibn Khalid Khan',
    featured: 'NIL',
    releaseDate: 'Upcoming...',
    genre: 'Pop',
    language: 'Bengali',
    type: 'Single',
    subgenre: 'NIL',
    copyright: 'Ibn Khalid Khan',
    composer: 'Ibn Khalid Khan, Afia Ibnat Snigdha',
    explicit: false,
    songwriter: 'Sohan Ali',
    platform: 'Upcoming Release',
    link: '#',
    coverImage: '/covers/Onno_Groher_Chand.png',
    spotifyId: null,
  },
];

export const ARTISTS = [
  {
    id: 1,
    name: 'OOLKA',
    role: 'The Core Project',
    bio: 'Emerging as a relentless force in the scene around 2025, OOLKA represents a sharp pivot into a heavier, uncompromising soundscape. A collaborative project bridging brutalist electronics with heavy rock and metal.',
    image: '/logo/oolka-logo.png',
    tracks: ['All'],
  },
  {
    id: 2,
    name: 'IBN KHALID KHAN',
    role: 'Heavy Synthesis, Guitars, Vocals, Production',
    bio: 'The architectural backbone of OOLKA. Ibn Khalid Khan wields blistering riffs, metallic dynamics, and dense atmospheric weight. His multi-instrumental mastery and raw production ethos define the project.',
    image: '/collaborators/ibn-khalid-khan.png',
    tracks: ['KITPOKA', 'ABSENCE', 'ASTRAY', 'CHUTI CHAY', 'DAKNAM', 'PANDAGIRL'],
  },
  {
    id: 3,
    name: 'RAFSAN JANI',
    role: 'Percussion, Sound Design',
    bio: "Rhythmic architect and sonic innovator. Rafsan Jani layers percussive complexity with meticulous sound design, creating the timbral foundation that anchors OOLKA's brutalist aesthetic.",
    image: '/collaborators/rafsan-jani.png',
    tracks: ['CHUTI CHAY', 'DAKNAM', 'KITPOKA', 'ASTRAY', 'QOOXX'],
  },
  {
    id: 5,
    name: 'MAHRUS HABIB',
    role: 'Rapper, MC',
    bio: 'Bringing sharp rhythmic cadences and aggressive verbal delivery. Mahrus Habib injects urban edge and fast-paced verse execution into experimental genre-bending tracks.',
    image: '/collaborators/mahrus-habib.png',
    tracks: ['BOSSIN'],
  },
  {
    id: 5,
    name: 'TASHFIQUE KAIF',
    role: 'Arranger, Sound Designer',
    bio: 'Architect of sonic spaces. Tashfique Kaif meticulously structures instrumental layers, ensuring the transition between aggressive rock elements and moody blues retains maximum impact.',
    image: '/collaborators/tashfique-kaif.png',
    tracks: ['SHEDIN DUPORE'],
  },
  {
    "id": 6,
    "name": "SHAHRIAR SAKIN",
    "role": "Vocalist",
    "bio": "Dynamic vocal performer delivering powerful grit and extensive range. Sakin handles high-energy vocal tracks that require an uncompromising rock and metal delivery.",
    "image": "/collaborators/shahriar-sakin.png",
    "tracks": ["ASTRAY"]
  },
  {
    "id": 7,
    "name": "DANIEL HASAN",
    "role": "Visuals, Cinematography",
    "bio": "The eye behind the monochromatic identity. Daniel Hasan translates the heavy, distorted, and minimalist audio landscapes of OOLKA into stark, high-contrast visual imagery.",
    "image": "/collaborators/daniel-hasan.png",
    "tracks": ["VISUAL DIRECTION / MUSIC VIDEOS"]
  },
  {
    id: 8,
    name: 'AFIA IBNAT SNIGDHA',
    role: 'Vocals, Lyrics',
    bio: 'Vocal presence and lyrical force. Afia Ibnat Snigdha brings ethereal yet commanding arrangements to select OOLKA Productions releases, grounding heavy instrumentation in intense human emotion.',
    image: '/collaborators/afia-snigdha.png',
    tracks: ['SHEDIN DUPORE'],
  },
];

export const BRANDS = [
  {
    id: 1,
    name: 'OOLKA Productions',
    type: 'Record Label / Production House',
    description: 'Main production house for OOLKA collaborative projects and releases. Spearheads all hard rock and metal output under the OOLKA banner.',
    focus: 'Hard Rock / Metal',
    logo: '/logo/oolka-logo-new.png',
    socials: {
      instagram: 'instagram.com/oolkatheband',
      spotify: 'https://open.spotify.com/artist/6ta2htFKHLD0JHUfYgdydO',
      youtube: 'https://www.youtube.com/@oolkatheband',
      appleMusic: 'https://music.apple.com/us/artist/oolka/1831394182',
    },
  },
  {
    id: 2,
    name: 'Ibn Khalid Khan',
    type: 'Solo Label',
    description: "Independent label for Ibn Khalid Khan's solo projects and collaborations outside the OOLKA collective. Features Blues, Rock, and Hip-Hop releases.",
    focus: 'Electronic / Ambient',
    logo: '/logo/khalid.png',
    socials: {
      instagram: 'instagram.com/realwithikk',
      spotify: 'https://open.spotify.com/artist/7xC3TczDpE3XkArdJzTrRA',
      youtube: 'https://www.youtube.com/@IbnKhalidKhan',
      appleMusic: 'https://music.apple.com/ke/artist/ibn-khalid-khan/1829760280',
    },
  },
  {
    id: 3,
    name: 'Ferric Box BD',
    type: 'Shop',
    description: "The only shop of OOLKA BD.",
    focus: 'Rock / Metal / Blues / Hip-Hop',
    logo: '/logo/26.png',
    socials: {
      instagram: '#',
      spotify: '#',
      youtube: '#',
      appleMusic: '#',
    },
  },
];

export const UPCOMING_CONCERTS = [
  {
    id: 1,
    venue: 'TBA – Dhaka',
    date: 'Q3 2026',
    city: 'Dhaka, Bangladesh',
    type: 'Headline Show',
    status: 'Announced',
  },
  {
    id: 2,
    venue: 'TBA – Online Livestream',
    date: 'Q4 2026',
    city: 'Global / YouTube',
    type: 'Livestream Release Event',
    status: 'Upcoming',
  },
  {
    id: 3,
    venue: 'TBA – Chittagong',
    date: '2027',
    city: 'Chittagong, Bangladesh',
    type: 'Tour Date',
    status: 'TBA',
  },
];

export const SETLIST_TRACKS = [
  { id: 1, title: 'ASTRAY', artist: 'OOLKA', energy: 'HEAVY', duration: '3:42' },
  { id: 2, title: 'KITPOKA', artist: 'Ibn Khalid Khan', energy: 'HEAVY', duration: '4:01' },
  { id: 3, title: 'CHUTI CHAY', artist: 'OOLKA', energy: 'MEDIUM', duration: '3:28' },
  { id: 4, title: 'ABSENCE', artist: 'Ibn Khalid Khan', energy: 'ACOUSTIC', duration: '5:10' },
  { id: 5, title: 'QOOXX', artist: 'OOLKA', energy: 'HEAVY', duration: '3:55' },
  { id: 6, title: 'TOMAR SHOHOR', artist: 'Ibn Khalid Khan', energy: 'ACOUSTIC', duration: '4:22' },
  { id: 7, title: 'EPISTOSIX', artist: 'OOLKA', energy: 'INSTRUMENTAL', duration: '6:08' },
  { id: 8, title: 'DAKNAM', artist: 'OOLKA', energy: 'HEAVY', duration: '3:31' },
];

export const SOCIAL_LINKS = {
  instagram: '#',
  spotify: '#',
  youtube: '#',
  appleMusic: '#',
};
